[package]
name = "erc_6806_holding_time_tracking"
version = "0.1.0"
edition = "2023_11"
cairo-version = "2.8.4"
scarb-version = "2.8.4"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = "2.8.4"
openzeppelin_access = "0.18.0"
openzeppelin_introspection = "0.18.0"
openzeppelin_token = "0.18.0"

[dev-dependencies]
snforge_std = "0.31.0"
assert_macros = "2.8.4"
openzeppelin_utils = "0.18.0"
openzeppelin_testing = "0.18.0"

[[target.starknet-contract]]
sierra = true

[scripts]
test = "snforge test"
